version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: 'unless-stopped'
    networks:
      - backend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: 'unless-stopped'
    networks:
      - backend
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  server:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: 'unless-stopped'
    networks:
      - backend
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
    driver: local
