###
# baseURL
@baseURL = http://localhost:3000/v1.0
@json = application/json

###
# @name signin
POST {{baseURL}}/signin
Content-Type: {{json}}

{
  "email": "tester2@gmail.com",
	"password": "123456789"
}

###
@authToken = {{signin.response.body.jwt}}
# @name getMatchCode
GET {{baseURL}}/match/code
Authorization: Bearer {{authToken}}
Content-Type: {{json}}

###
@matchCode = {{getMatchCode.response.body.value.matchCode}}
# Fill in match
POST {{baseURL}}/match
Authorization: Bearer {{authToken}}
Content-Type: {{json}}

{
  "value": {
    "matchCode": "{{matchCode}}"
  }
}

###
@authToken = {{signin.response.body.jwt}}
# Get match report
GET {{baseURL}}/match/5
Authorization: Bearer {{authToken}}
Content-Type: {{json}}

###
@authToken = {{signin.response.body.jwt}}
# Get match history
GET {{baseURL}}/match
Authorization: Bearer {{authToken}}
Content-Type: {{json}}

###
@authToken = {{signin.response.body.jwt}}
# Delete match
DELETE {{baseURL}}/match/5
Authorization: Bearer {{authToken}}
Content-Type: {{json}}