###
# baseURL
@baseURL = http://localhost:3000/v1.0
@json = application/json

###
# @name signin
POST {{baseURL}}/signin
Content-Type: {{json}}

{
  "email": "tester@gmail.com",
	"password": "123456789"
}

###
@authToken = {{signin.response.body.jwt}}
# Get 10 questions
GET {{baseURL}}/questions
Authorization: Bearer {{authToken}}
Content-Type: {{json}}


###
@authToken = {{signin.response.body.jwt}}
# Get a question by id
GET {{baseURL}}/questions/1
Authorization: Bearer {{authToken}}
Content-Type: {{json}}


###
@authToken = {{signin.response.body.jwt}}
# Get statistics for question
GET {{baseURL}}/questions/1/statistics
Authorization: Bearer {{authToken}}
Content-Type: {{json}}
