###
# baseURL
@baseURL = http://localhost:3000/v1.0
@json = application/json

###
# @name signin
POST {{baseURL}}/signin
Content-Type: {{json}}

{
  "email": "tester@gmail.com",
	"password": "123456789"
}

###
@authToken = {{signin.response.body.jwt}}
# Send responses to a question
POST {{baseURL}}/responses
Authorization: Bearer {{authToken}}
Content-Type: {{json}}

{
  "responses": [
    { "optionId": 0, "questionId": 3 },
    { "optionId": 2, "questionId": 3 }
  ]
}